### PR TITLE
Added a new room called 'PigeonHouse'

### PR DESCRIPTION
**Pull request by Jonah-gr**
This new room allows players to explore an abandoned pigeon house within the ZDD environment. The room presents an option to open an old window, triggering different outcomes based on the player's choice. If the player decides to open the window, they will discover a baby pigeon, leading to an 'opportunity' to have the pigeon as a companion.

### CODE REVIEW

**Review by sekkurocode — APPROVED** [review]
The story is delightful and the room is implemented well into the code infrastructure. Approve this pull request to be merged with zdd_adventure main branch.

**Review by honnigmelone — APPROVED** [review]
Well done, very interesting interactive story that you came up with. I really like the Pigeon- Room 👍  Approved!

**Comment by honnigmelone** [comment]
@l4nz8 pull request ready to be merged!

**Comment by l4nz8** [comment]
Clean✨, the only thing I might add is a way to interact with your companion.

**Pull request merged**
