### PR TITLE
Solved issue #02

### PR DESCRIPTION
**Pull request by tis22**
Added the fridge-item to the kitchen-room.
Created the kitchen-story:
The user can collect the recipes now.
The user can take a look into the fridge and take items out of it (to his inventory) now.
After looking into the fridge the user can decide if he wants to eat some of the collected items.
The user can eat items from the fridge only.
If he hasn't items from the fridge in his inventory (or hasn't anymore) he can't eat something.
Items eaten disappear completely, they can't be obtained again.

### CODE REVIEW

**Review by Jonah-gr — APPROVED** [review]
Good job!

**Comment by l4nz8** [comment]
Nice features, but you don't need to move the enter_room function from `main_classes.py` to the KitchenFirstFloor(Room) class as it can already use the function. Just try editing the `zdd_rooms.py` and `zdd_adventure.py` as I recommended in the other pull request #13.

**Comment by tis22** [comment]
The enter_room function was modified so that the user can only look into the fride **after** the user decided to inspect the room.
Otherwise the story would go through first (as it is defined in the enter_room-method in `main_classes.py`).
If you have an other idea, how the story can only be accessed, if the user inspects the room, please explain it to me, thank you.

**Comment by l4nz8** [comment]
I'm sorry, I took another look at your room and it works fine. I didn't know exactly what you had in mind in the other pull request #13, as you have only defined a room without any content there.

**Review by l4nz8 — APPROVED** [review]
works perfectly

**Pull request merged**
