### PR TITLE
Added new item "baby pigeon"

### PR DESCRIPTION
**Pull request by Jonah-gr**
The new item can be found in the pigeon house. It's a baby pigeon which only makes 'gurrr!'.

### CODE REVIEW

**Review by sekkurocode — APPROVED** [review]
Looks good. Added baby pigeon as a moveable item and appended it into the players Inventory. Good job!

**Review by honnigmelone — APPROVED** [review]
Nicely done as well, or as the pigeon would say "gurrrr". It's a great addition to your room! Also approved 👍  how can people say no to a baby pigeon?!

**Comment by honnigmelone** [comment]
@l4nz8 pull request ready to be merged!

**Comment by l4nz8** [comment]
Perfect

**Pull request merged**
